/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import logica.Proceso;
import vista.JFrPedirProcesos;

/**
 *
 * @author Eleana Hurtado
 */
public class JFrCapDatosProcesos extends javax.swing.JFrame {

    /**
     * Creates new form JFrCapDatosProcesos
     */
    public JFrCapDatosProcesos() {
        initComponents();
        this.setLocationRelativeTo(null);

    }
    public static Proceso[] procesos = new Proceso[JFrPedirProcesos.num_proc+1];
    static int posicion = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeltitulo = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jTextFieldNombreProceso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTiempoLlegada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTiempoCPU = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPrioridad = new javax.swing.JTextField();
        jButtonGuardarDatos = new javax.swing.JButton();
        jLabelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeltitulo.setText("Ingrese los datos del proceso:");
        getContentPane().add(jLabeltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabelID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelID.setText("Nombre: ");
        getContentPane().add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jTextFieldNombreProceso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldNombreProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 90, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Tiempo de llegada:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 20));

        jTextFieldTiempoLlegada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldTiempoLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 90, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tiempo de CPU:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jTextFieldTiempoCPU.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldTiempoCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTiempoCPUActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTiempoCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Prioridad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jTextFieldPrioridad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 90, -1));

        jButtonGuardarDatos.setBackground(new java.awt.Color(0, 0, 102));
        jButtonGuardarDatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonGuardarDatos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardarDatos.setText("Guardar");
        jButtonGuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 90, 30));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4c6c326026c11aa31a94f442170502c9.jpg"))); // NOI18N
        getContentPane().add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -200, 450, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTiempoCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTiempoCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTiempoCPUActionPerformed

    private void jButtonGuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarDatosActionPerformed
        // TODO add your handling code here:

        int si = 1;
        if (jTextFieldNombreProceso.getText().isEmpty() || jTextFieldPrioridad.getText().isEmpty() || jTextFieldTiempoCPU.getText().isEmpty() || jTextFieldTiempoLlegada.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "INGRESE TODOS LOS DATOS", null, JOptionPane.ERROR_MESSAGE);
            si = 0;
        }

        String auxNombre = "";
        float auxPrioridad = 0, auxTiempoCPU = 0, auxTiempoLlegada = 0;
        auxNombre = jTextFieldNombreProceso.getText();
        try {
            
            auxPrioridad = Float.parseFloat(jTextFieldPrioridad.getText());
            auxTiempoCPU = Float.parseFloat(jTextFieldTiempoCPU.getText());
            auxTiempoLlegada = Float.parseFloat(jTextFieldTiempoLlegada.getText());
            if(auxPrioridad<0 || auxTiempoCPU<1 || auxTiempoLlegada<0){
              JOptionPane.showMessageDialog(null, "Digite números positivos", null, JOptionPane.ERROR_MESSAGE);
              si = 0;  
            }
        } catch (NumberFormatException | NullPointerException e) {
            JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage(), null, JOptionPane.ERROR_MESSAGE);
            si = 0;
        }
        procesos[posicion]=new Proceso(auxNombre, auxTiempoLlegada, auxTiempoCPU, auxPrioridad);

        if (si == 1) {
            if (JFrPedirProcesos.num_proc == 0) {
                for (int x = 0; x < procesos.length; x++) {
                    System.out.println(procesos[x].toString());
                }
                JOptionPane.showMessageDialog(null, "Datos guardados exitosamente");
                JFrMenu Menu = new JFrMenu();
                this.setVisible(false);
                Menu.setVisible(true);

            } else {
                this.setVisible(false);
                jTextFieldNombreProceso.setText("");
                jTextFieldPrioridad.setText("");
                jTextFieldTiempoCPU.setText("");
                jTextFieldTiempoLlegada.setText("");
                System.out.println(JFrPedirProcesos.num_proc);
                JFrPedirProcesos.num_proc = JFrPedirProcesos.num_proc - 1;
                this.setVisible(true);
                posicion++;
                System.out.println(posicion);

            }
        }

    }//GEN-LAST:event_jButtonGuardarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrCapDatosProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrCapDatosProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrCapDatosProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrCapDatosProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrCapDatosProcesos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardarDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JLabel jLabeltitulo;
    private javax.swing.JTextField jTextFieldNombreProceso;
    private javax.swing.JTextField jTextFieldPrioridad;
    private javax.swing.JTextField jTextFieldTiempoCPU;
    private javax.swing.JTextField jTextFieldTiempoLlegada;
    // End of variables declaration//GEN-END:variables
}
