/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import logica.Algoritmo;
import static vista.JFrCapDatosProcesos.procesos;

/**
 *
 * @author Eleana Hurtado
 */
public class JFrMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFrMenu
     */
    public JFrMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    Algoritmo algoritmos = new Algoritmo();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFIFO = new javax.swing.JButton();
        jButtonSJF = new javax.swing.JButton();
        jButtonPrioridadEXPNO = new javax.swing.JButton();
        jButtonPrioridadEXP = new javax.swing.JButton();
        jButtonSRTF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonFIFO.setBackground(new java.awt.Color(153, 255, 255));
        jButtonFIFO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonFIFO.setText("FIFO");
        jButtonFIFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFIFOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFIFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 83, 140, 30));

        jButtonSJF.setBackground(new java.awt.Color(153, 255, 255));
        jButtonSJF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSJF.setText("SJF");
        getContentPane().add(jButtonSJF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 133, 140, 30));

        jButtonPrioridadEXPNO.setBackground(new java.awt.Color(153, 255, 255));
        jButtonPrioridadEXPNO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPrioridadEXPNO.setText("Prioridad EXP-NO");
        getContentPane().add(jButtonPrioridadEXPNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 140, 30));

        jButtonPrioridadEXP.setBackground(new java.awt.Color(153, 255, 255));
        jButtonPrioridadEXP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPrioridadEXP.setText("Prioridad EXP");
        getContentPane().add(jButtonPrioridadEXP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 140, 30));

        jButtonSRTF.setBackground(new java.awt.Color(153, 255, 255));
        jButtonSRTF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSRTF.setText("SRTF");
        getContentPane().add(jButtonSRTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 140, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Elija un algoritmo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/83bb374c7295613ac86b18cb5f93edbc.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 380, 350));
        getContentPane().add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFIFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFIFOActionPerformed
        // TODO add your handling code here:
        algoritmos.fifo(procesos);
    }//GEN-LAST:event_jButtonFIFOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButtonFIFO;
    private javax.swing.JButton jButtonPrioridadEXP;
    private javax.swing.JButton jButtonPrioridadEXPNO;
    private javax.swing.JButton jButtonSJF;
    private javax.swing.JButton jButtonSRTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
