/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Eleana Hurtado
 */
public class JFrPedirProcesos extends javax.swing.JFrame {

    /**
     * Creates new form JFrPedirProcesos
     */
    
    public JFrPedirProcesos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public static int num_proc = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeltitulo = new javax.swing.JLabel();
        jComboBoxProcesos = new javax.swing.JComboBox<>();
        jButtonAceptar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltitulo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabeltitulo.setText("¿Cuantos procesos desea simular?");
        getContentPane().add(jLabeltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 260, 30));

        jComboBoxProcesos.setBackground(new java.awt.Color(204, 255, 255));
        jComboBoxProcesos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxProcesos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "5", "6", "7", "8" }));
        jComboBoxProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProcesosActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxProcesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 50, 30));

        jButtonAceptar.setBackground(new java.awt.Color(0, 153, 255));
        jButtonAceptar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 160, 100, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4c6c326026c11aa31a94f442170502c9.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProcesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProcesosActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        
        String procesos = (String)jComboBoxProcesos.getSelectedItem();
        num_proc = Integer.parseInt(procesos)-1;
   
        JFrCapDatosProcesos CapDatos = new JFrCapDatosProcesos();
        CapDatos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrPedirProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrPedirProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrPedirProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrPedirProcesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrPedirProcesos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JComboBox<String> jComboBoxProcesos;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabeltitulo;
    // End of variables declaration//GEN-END:variables
}
